/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceReaderRouteImport } from './routes/voice-reader'
import { Route as TopicClassificationRouteImport } from './routes/topic-classification'
import { Route as TextSummarizationRouteImport } from './routes/text-summarization'
import { Route as SpamDetectionRouteImport } from './routes/spam-detection'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SentimentAnalysisRouteImport } from './routes/sentiment-analysis'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RealTimePredictionsRouteImport } from './routes/real-time-predictions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NamedEntityRecognitionRouteImport } from './routes/named-entity-recognition'
import { Route as ModelRouteImport } from './routes/model'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageTranslationRouteImport } from './routes/language-translation'
import { Route as LanguageDetectionRouteImport } from './routes/language-detection'
import { Route as KeywordExtractionRouteImport } from './routes/keyword-extraction'
import { Route as ImageAnalyzerRouteImport } from './routes/image-analyzer'
import { Route as HateSpeechDetectionRouteImport } from './routes/hate-speech-detection'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as EmotionRecognitionRouteImport } from './routes/emotion-recognition'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiTextInsightsRouteImport } from './routes/ai-text-insights'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VoiceReaderRoute = VoiceReaderRouteImport.update({
  id: '/voice-reader',
  path: '/voice-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicClassificationRoute = TopicClassificationRouteImport.update({
  id: '/topic-classification',
  path: '/topic-classification',
  getParentRoute: () => rootRouteImport,
} as any)
const TextSummarizationRoute = TextSummarizationRouteImport.update({
  id: '/text-summarization',
  path: '/text-summarization',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamDetectionRoute = SpamDetectionRouteImport.update({
  id: '/spam-detection',
  path: '/spam-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentAnalysisRoute = SentimentAnalysisRouteImport.update({
  id: '/sentiment-analysis',
  path: '/sentiment-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RealTimePredictionsRoute = RealTimePredictionsRouteImport.update({
  id: '/real-time-predictions',
  path: '/real-time-predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NamedEntityRecognitionRoute = NamedEntityRecognitionRouteImport.update({
  id: '/named-entity-recognition',
  path: '/named-entity-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageTranslationRoute = LanguageTranslationRouteImport.update({
  id: '/language-translation',
  path: '/language-translation',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageDetectionRoute = LanguageDetectionRouteImport.update({
  id: '/language-detection',
  path: '/language-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const KeywordExtractionRoute = KeywordExtractionRouteImport.update({
  id: '/keyword-extraction',
  path: '/keyword-extraction',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageAnalyzerRoute = ImageAnalyzerRouteImport.update({
  id: '/image-analyzer',
  path: '/image-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const HateSpeechDetectionRoute = HateSpeechDetectionRouteImport.update({
  id: '/hate-speech-detection',
  path: '/hate-speech-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const EmotionRecognitionRoute = EmotionRecognitionRouteImport.update({
  id: '/emotion-recognition',
  path: '/emotion-recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTextInsightsRoute = AiTextInsightsRouteImport.update({
  id: '/ai-text-insights',
  path: '/ai-text-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-text-insights': typeof AiTextInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/emotion-recognition': typeof EmotionRecognitionRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hate-speech-detection': typeof HateSpeechDetectionRoute
  '/image-analyzer': typeof ImageAnalyzerRoute
  '/keyword-extraction': typeof KeywordExtractionRoute
  '/language-detection': typeof LanguageDetectionRoute
  '/language-translation': typeof LanguageTranslationRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/named-entity-recognition': typeof NamedEntityRecognitionRoute
  '/profile': typeof ProfileRoute
  '/real-time-predictions': typeof RealTimePredictionsRoute
  '/register': typeof RegisterRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/signup': typeof SignupRoute
  '/spam-detection': typeof SpamDetectionRoute
  '/text-summarization': typeof TextSummarizationRoute
  '/topic-classification': typeof TopicClassificationRoute
  '/voice-reader': typeof VoiceReaderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-text-insights': typeof AiTextInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/emotion-recognition': typeof EmotionRecognitionRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hate-speech-detection': typeof HateSpeechDetectionRoute
  '/image-analyzer': typeof ImageAnalyzerRoute
  '/keyword-extraction': typeof KeywordExtractionRoute
  '/language-detection': typeof LanguageDetectionRoute
  '/language-translation': typeof LanguageTranslationRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/named-entity-recognition': typeof NamedEntityRecognitionRoute
  '/profile': typeof ProfileRoute
  '/real-time-predictions': typeof RealTimePredictionsRoute
  '/register': typeof RegisterRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/signup': typeof SignupRoute
  '/spam-detection': typeof SpamDetectionRoute
  '/text-summarization': typeof TextSummarizationRoute
  '/topic-classification': typeof TopicClassificationRoute
  '/voice-reader': typeof VoiceReaderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-text-insights': typeof AiTextInsightsRoute
  '/analytics': typeof AnalyticsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/emotion-recognition': typeof EmotionRecognitionRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/hate-speech-detection': typeof HateSpeechDetectionRoute
  '/image-analyzer': typeof ImageAnalyzerRoute
  '/keyword-extraction': typeof KeywordExtractionRoute
  '/language-detection': typeof LanguageDetectionRoute
  '/language-translation': typeof LanguageTranslationRoute
  '/login': typeof LoginRoute
  '/model': typeof ModelRoute
  '/named-entity-recognition': typeof NamedEntityRecognitionRoute
  '/profile': typeof ProfileRoute
  '/real-time-predictions': typeof RealTimePredictionsRoute
  '/register': typeof RegisterRoute
  '/sentiment-analysis': typeof SentimentAnalysisRoute
  '/signup': typeof SignupRoute
  '/spam-detection': typeof SpamDetectionRoute
  '/text-summarization': typeof TextSummarizationRoute
  '/topic-classification': typeof TopicClassificationRoute
  '/voice-reader': typeof VoiceReaderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-text-insights'
    | '/analytics'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/emotion-recognition'
    | '/features'
    | '/forgot-password'
    | '/hate-speech-detection'
    | '/image-analyzer'
    | '/keyword-extraction'
    | '/language-detection'
    | '/language-translation'
    | '/login'
    | '/model'
    | '/named-entity-recognition'
    | '/profile'
    | '/real-time-predictions'
    | '/register'
    | '/sentiment-analysis'
    | '/signup'
    | '/spam-detection'
    | '/text-summarization'
    | '/topic-classification'
    | '/voice-reader'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-text-insights'
    | '/analytics'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/emotion-recognition'
    | '/features'
    | '/forgot-password'
    | '/hate-speech-detection'
    | '/image-analyzer'
    | '/keyword-extraction'
    | '/language-detection'
    | '/language-translation'
    | '/login'
    | '/model'
    | '/named-entity-recognition'
    | '/profile'
    | '/real-time-predictions'
    | '/register'
    | '/sentiment-analysis'
    | '/signup'
    | '/spam-detection'
    | '/text-summarization'
    | '/topic-classification'
    | '/voice-reader'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-text-insights'
    | '/analytics'
    | '/contact'
    | '/dashboard'
    | '/demo'
    | '/emotion-recognition'
    | '/features'
    | '/forgot-password'
    | '/hate-speech-detection'
    | '/image-analyzer'
    | '/keyword-extraction'
    | '/language-detection'
    | '/language-translation'
    | '/login'
    | '/model'
    | '/named-entity-recognition'
    | '/profile'
    | '/real-time-predictions'
    | '/register'
    | '/sentiment-analysis'
    | '/signup'
    | '/spam-detection'
    | '/text-summarization'
    | '/topic-classification'
    | '/voice-reader'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiTextInsightsRoute: typeof AiTextInsightsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  EmotionRecognitionRoute: typeof EmotionRecognitionRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HateSpeechDetectionRoute: typeof HateSpeechDetectionRoute
  ImageAnalyzerRoute: typeof ImageAnalyzerRoute
  KeywordExtractionRoute: typeof KeywordExtractionRoute
  LanguageDetectionRoute: typeof LanguageDetectionRoute
  LanguageTranslationRoute: typeof LanguageTranslationRoute
  LoginRoute: typeof LoginRoute
  ModelRoute: typeof ModelRoute
  NamedEntityRecognitionRoute: typeof NamedEntityRecognitionRoute
  ProfileRoute: typeof ProfileRoute
  RealTimePredictionsRoute: typeof RealTimePredictionsRoute
  RegisterRoute: typeof RegisterRoute
  SentimentAnalysisRoute: typeof SentimentAnalysisRoute
  SignupRoute: typeof SignupRoute
  SpamDetectionRoute: typeof SpamDetectionRoute
  TextSummarizationRoute: typeof TextSummarizationRoute
  TopicClassificationRoute: typeof TopicClassificationRoute
  VoiceReaderRoute: typeof VoiceReaderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-reader': {
      id: '/voice-reader'
      path: '/voice-reader'
      fullPath: '/voice-reader'
      preLoaderRoute: typeof VoiceReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-classification': {
      id: '/topic-classification'
      path: '/topic-classification'
      fullPath: '/topic-classification'
      preLoaderRoute: typeof TopicClassificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-summarization': {
      id: '/text-summarization'
      path: '/text-summarization'
      fullPath: '/text-summarization'
      preLoaderRoute: typeof TextSummarizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam-detection': {
      id: '/spam-detection'
      path: '/spam-detection'
      fullPath: '/spam-detection'
      preLoaderRoute: typeof SpamDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment-analysis': {
      id: '/sentiment-analysis'
      path: '/sentiment-analysis'
      fullPath: '/sentiment-analysis'
      preLoaderRoute: typeof SentimentAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/real-time-predictions': {
      id: '/real-time-predictions'
      path: '/real-time-predictions'
      fullPath: '/real-time-predictions'
      preLoaderRoute: typeof RealTimePredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/named-entity-recognition': {
      id: '/named-entity-recognition'
      path: '/named-entity-recognition'
      fullPath: '/named-entity-recognition'
      preLoaderRoute: typeof NamedEntityRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-translation': {
      id: '/language-translation'
      path: '/language-translation'
      fullPath: '/language-translation'
      preLoaderRoute: typeof LanguageTranslationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language-detection': {
      id: '/language-detection'
      path: '/language-detection'
      fullPath: '/language-detection'
      preLoaderRoute: typeof LanguageDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyword-extraction': {
      id: '/keyword-extraction'
      path: '/keyword-extraction'
      fullPath: '/keyword-extraction'
      preLoaderRoute: typeof KeywordExtractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-analyzer': {
      id: '/image-analyzer'
      path: '/image-analyzer'
      fullPath: '/image-analyzer'
      preLoaderRoute: typeof ImageAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hate-speech-detection': {
      id: '/hate-speech-detection'
      path: '/hate-speech-detection'
      fullPath: '/hate-speech-detection'
      preLoaderRoute: typeof HateSpeechDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emotion-recognition': {
      id: '/emotion-recognition'
      path: '/emotion-recognition'
      fullPath: '/emotion-recognition'
      preLoaderRoute: typeof EmotionRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-text-insights': {
      id: '/ai-text-insights'
      path: '/ai-text-insights'
      fullPath: '/ai-text-insights'
      preLoaderRoute: typeof AiTextInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiTextInsightsRoute: AiTextInsightsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  EmotionRecognitionRoute: EmotionRecognitionRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HateSpeechDetectionRoute: HateSpeechDetectionRoute,
  ImageAnalyzerRoute: ImageAnalyzerRoute,
  KeywordExtractionRoute: KeywordExtractionRoute,
  LanguageDetectionRoute: LanguageDetectionRoute,
  LanguageTranslationRoute: LanguageTranslationRoute,
  LoginRoute: LoginRoute,
  ModelRoute: ModelRoute,
  NamedEntityRecognitionRoute: NamedEntityRecognitionRoute,
  ProfileRoute: ProfileRoute,
  RealTimePredictionsRoute: RealTimePredictionsRoute,
  RegisterRoute: RegisterRoute,
  SentimentAnalysisRoute: SentimentAnalysisRoute,
  SignupRoute: SignupRoute,
  SpamDetectionRoute: SpamDetectionRoute,
  TextSummarizationRoute: TextSummarizationRoute,
  TopicClassificationRoute: TopicClassificationRoute,
  VoiceReaderRoute: VoiceReaderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
